# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
  displayName: 'Install Rust'

- script: |
    cd syslog5424
    cargo test --verbose
  displayName: 'Run tests'
